name: fluent
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

topics:
  - windows
  - desktop
  - ui
  - widgets

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Used on date and time pickers
  intl: '>=0.18.0 <= 1.0.0'

  # Used on TabView
  scroll_pos: '>=0.5.0 < 1.0.0'

  # Used on icon generator
  recase: ^4.1.0

  # Used on NumberBox
  math_expressions: ^2.4.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  intl_utils: ^2.8.3

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/AcrylicNoise.png
  fonts:
    - family: FluentIcons
      fonts:
        - asset: fonts/FluentIcons.ttf

  module:
    androidX: true
    androidPackage: com.trong.fluent
    iosBundleIdentifier: com.trong.fluent
